---
- name: Import des variables de la distribution.
  ansible.builtin.include_vars:
    file: defaults/fedora.yml

- name: Gestion de QEMU.
  ansible.builtin.import_tasks:
    file: fedora/qemu.yml

- name: Configuration de dnf5.
  ansible.builtin.import_tasks:
    file: fedora/dnf5.yml

- name: Configuration du SSH.
  ansible.builtin.import_tasks:
    file: fedora/ssh.yml

- name: Redémarrage du serveur.
  ansible.builtin.reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
