---
- name: Augmentation de la sécurité des mots de passe.
  lineinfile:
    path: /etc/pam.d/passwd
    line: "password   required     pam_unix.so sha512 shadow nullok rounds=65536"
    owner: root
    group: root
    mode: '0644'
    state: present
    backup: no

- name: Modification de la variable umask et de la méthode de chiffrement.
  lineinfile:
    path: /etc/login.defs
    regexp: "{{ item.regex }}"
    line: "{{ item.ligne }}"
    owner: root
    group: root
    mode: '0644'
    state: present
  with_items:
    - { regex: '^UMASK', ligne: 'UMASK           027' }
    - { regex: '^ENCRYPT_METHOD', ligne: 'ENCRYPT_METHOD SHA512' }

- name: Mise à jour du mot de passe root.
  user:
    name: root
    state: present
    password: "{{ new_passwd | password_hash('sha512', 'SebAsTuX') }}"
    update_password: always

- name: Création d'une clé ssh pour le compte root.
  openssh_keypair:
    path: "../cles_ssh/root"
    backend: cryptography
    comment: "Clé SSH généré par ansible."
    mode: 0600
    regenerate: always
    state: present
    type: ed25519
  delegate_to: localhost

- name: Installation de la clé sur le compte.
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '../cles_ssh/root.pub') }}"
    comment: "Clé SSH généré et installé par ansible."
    exclusive: yes
    manage_dir: yes

- name: Installation des packages du rôle.
  apt:
    name: "{{ liste_install }}"
    state: latest
    update_cache: yes

- name: Démarrage du pare-feu.
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Ouverture de port pour divers services.
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - http
    - https
    - cockpit

- name: Installation du fichier de configuration du ssh.
  template:
    src: templates/sshd_config_modif.j2
    dest: /etc/ssh/sshd_config.d/sshd_ansible.conf
    backup: no
    owner: root
    group: root
    mode: 0644

- name: Suppression du port SSH par défaut.
  firewalld:
    service: ssh
    permanent: yes
    state: disabled
    immediate: no

- name: Ouverture du nouveau port SSH.
  firewalld:
    port: "{{ new_ssh_port }}/tcp"
    permanent: yes
    state: enabled
    immediate: no

- name: Suppression de la mise à jour du motd.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/10-uname
    - /etc/issue.d/cockpit.issue
    - /etc/motd.d/cockpit

- name: Ajout d’adresse IP en liste blanche du pare feu.
  firewalld:
    source: "{{ ip_whitelist }}"
    state: enabled
    permanent: yes

- name: Redémarrage du serveur.
  reboot:
    msg: "Redémarrage automatique du serveur par ansible."
    connect_timeout: 5
    reboot_timeout: 60
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  ignore_errors: True

- name: Mise à jour du port SSH.
  set_fact:
     ansible_port: "{{ new_ssh_port }}"
