---
- name: Modiffication du chiffrement du mot de passe.
  community.general.pamd:
    name: passwd
    type: password
    new_type: password
    control: substack
    module_path: postlogin
    new_module_path: pam_unix.so
    backup: false
    new_control: required
    module_arguments: 'sha512 shadow nullok rounds=65536'
    state: after

# Restreindre l'accès à su aux membres du groupe wheel uniquement
- name: Restreindre su au groupe wheel.
  ansible.builtin.lineinfile:
    path: /etc/pam.d/su
    regexp: '^#?auth\s+required\s+pam_wheel.so'
    line: 'auth required pam_wheel.so use_uid'
    state: present
    backup: true

