---
- name: Installation de fail2ban.
  ansible.builtin.dnf5:
    name: "{{ fail2ban }}"
    state: latest
    update_cache: false

- name: Création d'un répertoire de surcharge fail2ban.
  ansible.builtin.file:
    path: /etc/systemd/system/fail2ban.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Installation de la configuration de fail2ban.
  ansible.builtin.template:
    src: "{{ item.fichier }}"
    dest: "{{ item.chemin }}"
    backup: false
    owner: root
    group: root
    mode: '0644'
  loop:
    - {fichier: 'fail2ban.j2', chemin: '/etc/fail2ban/jail.local'}
    - {fichier: 'fail2ban-ssh.j2', chemin: '/etc/fail2ban/jail.d/01-sshd.local'}
    - {fichier: 'durcissemnt.j2', chemin: '/etc/systemd/system/fail2ban.service.d/durcissemnt.conf'}

- name: Active fail2ban au démarrage.
  ansible.builtin.systemd_service:
    name: fail2ban
    enabled: true
    daemon-reload: true
    state: restarted
